version: '3.8'

services:
  web:
    build: .
    ports:
      - "4001:80"
    volumes:
      - ./:/var/www/html
    networks:
      - project

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: pass123
    networks:
      - project

  db:
    image: mariadb:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: serverside
      MYSQL_USER: serveruser
      MYSQL_PASSWORD: gorgonzola7!
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - project

networks:
  project:

volumes:
  db_data:
